#!/bin/env racket
#lang racket

(require "my-macro.rkt")

;; -- build ast --
(struct token (action number left right) #:mutable)
(define end (token 'end 0 '() '()))
(define stack '())
(define/contract (tokenize code) (-> string? token?)
  (let* ((current (token 'null 0 end end))
        (head current))
    (for ((ch code))
      (case ch
        ((#\+)
         (if (equal? (token-action current) 'add)
             (set-token-number! current (+ 1 (token-number current)))
             (let ((temp (token 'add 1 end end)))
               (set-token-left! current temp)
               (set! current temp))))
        ((#\-)
         (if (equal? (token-action current) 'add)
             (set-token-number! current (- (token-number current) 1))
             (let ((temp (token 'add -1 end end)))
               (set-token-left! current temp)
               (set! current temp))))
        ((#\<)
         (if (equal? (token-action current) 'move)
             (set-token-number! current (- (token-number current) 1))
             (let ((temp (token 'move -1 end end)))
               (set-token-left! current temp)
               (set! current temp))))
        ((#\>)
         (if (equal? (token-action current) 'move)
             (set-token-number! current (+ (token-number current) 1))
             (let ((temp (token 'move 1 end end)))
               (set-token-left! current temp)
               (set! current temp))))
        ((#\.)
         (let ((temp (token 'out 1 end end)))
           (set-token-left! current temp)
           (set! current temp)))
        ((#\,)
         (let ((temp (token 'in 1 end end)))
           (set-token-left! current temp)
           (set! current temp)))
        ((#\[)
         (let ((temp (token 'l-braket 1 end end)))
           (set-token-left! current temp)
           (set! current temp)
           (set! stack (cons temp stack))))
        ((#\])
         (let ((temp (token 'r-braket 1 end end)))
           (set-token-left! current temp)
           (set! current temp)
           (if (null? stack)
               (error "backet not match, too much ]")
               (begin
                 (set-token-right! (car stack) temp)
                 (set-token-right! temp (car stack))
                 (set! stack (cdr stack))))))))
    (if (null? stack)
        head
        (error "braket not match, too much ["))))

;; -- eval ast --
(define array (make-vector 10 0))
(define pointer 0)
(define (moveto k)
  (when (< k 0) (error "too left"))
  (while (<= (vector-length array) k)
    (let ((temp (make-vector (* 2 (vector-length array)) 0)))
      (vector-copy! temp 0 array)
      (set! array temp))))
(define/contract (eval-bf t) (-> token? any/c)
  (case (token-action t)
        ((add)
         (let ((num (vector-ref array pointer))
               (k (token-number t)))
           (vector-set! array pointer (+ num k))
           (eval-bf (token-left t))))
        ((move)
         (begin
           (set! pointer (+ pointer (token-number t)))
           (moveto pointer)
           (eval-bf (token-left t))))
        ((out)
         (begin
           (write-char (integer->char (vector-ref array pointer)))
           (eval-bf (token-left t))))
        ((in)
         (begin (vector-set! array pointer
                             (char->integer (read-char)))
                (eval-bf (token-left t))))
        ((l-braket)
         (if (= (vector-ref array pointer) 0)
             (eval-bf (token-right t))
             (eval-bf (token-left t))))
        ((r-braket)
         (if (= (vector-ref array pointer) 0)
             (eval-bf (token-left t))
             (eval-bf (token-right t))))
        ((null)
         (eval-bf (token-left t)))))

;; -- compile to c code --
(define prelog
  "#include<stdlib.h>\n#include<stdio.h>\n#include<string.h>\ntypedef struct{char* content;int capacity;int pointer;}array;\nvoid move(array* a,int position){a->pointer+=position;if(a->pointer<0){printf(\"too left\");exit(1);}while(a->capacity<=a->pointer){a->content=realloc(a->content,2*a->capacity*sizeof(char));memset(a->content + a->capacity, 0, a->capacity);a->capacity*=2;}}\nint main(){array a={.content=calloc(10,sizeof(char)),.capacity=10,.pointer=0,};")
(define enpilog "\nputchar('\\n');\nfree(a.content);\nreturn 0;}")
(define/contract (bf-compile t pre) (-> token? string? string?)
  (if (equal? (token-action t) 'end)
    pre
    (let ((code ""))
      (case (token-action t)
        ((add) (set! code (format "a.content[a.pointer]+=~a;\n" (token-number t))))
        ((move) (set! code (format "move(&a,~a);\n" (token-number t))))
        ((out) (set! code "putchar(a.content[a.pointer]);\n"))
        ((in) (set! code "a.content[a.pointer]=getchar();\n"))
        ((l-braket) (set! code "while(a.content[a.pointer]!=0){\n"))
        ((r-braket) (set! code "}\n")))
      (bf-compile (token-left t) (string-append pre code)))))

;; -- mian --
(define/contract (bf-compile-to-file name tokens) (-> string? token? any/c)
    (let ((s (string-append prelog (bf-compile tokens "") enpilog)))
    (call-with-output-file (string-append name ".c")
      (lambda (out) (display s out))
      #:exists 'replace)
    (if (system (string-append "cc " name ".c -o " name))
        (begin (printf "compiled cussessfully to: ~a" name)
               (delete-file (string->path (string-append name ".c"))))
        (error "failed to compile"))))

(define (main)
  (let* ((arguments (vector->list (current-command-line-arguments)))
         (mode (car arguments)))
    (case mode
      (("--eval" "-e") (->> arguments cadr tokenize eval-bf))
      (("--run" "-r") (->> arguments cadr string->path file->string tokenize eval-bf))
      (("--compile" "-c")
       (let ((filename "output")
             (args arguments))
         (while (->> args cdr (equal? '()) not)
           (when (or (equal? (car args) "--output")
                     (equal? (car args) "-o"))
             (set! filename (cadr args)))
           (set! args (cdr args)))
         (->> arguments cadr
              string->path file->string tokenize (bf-compile-to-file filename))))
      (else
       (display "usage: brainfuck [option] <file.bf>
      -e/--eval:    to evaluate a single sentence
      -r/--run:     to run the code with interpreter
      -c/--compile: to compile
      -o/--output:  to name the compile output
      -h/--help:    to get help"))))
  (newline))
(main)
